-- require('config.globals')
require('config.options')
require('config.keymaps')
-- require('plugins.themes')
-- require('plugins.nvim-treesitter')
require("plugins.pack")
require("current-theme")
vim.loader.enable()